### ISSUE TITLE
fix: AAR should not use app release version

### ISSUE THREAD

**Issue by LammPhan** [shorebirdtech/samples#11]
**Description**

I'm setting code push for flutter module on platform android app native. My current flutter version is 3.13.9. 
my config app native is 
```gradle
defaultConfig {
       ...
        versionCode 1
        versionName "1.0.0"
       ...
    }
```
I created library aar by command 
`shorebird release aar --release-version 1.0.0+1 --flutter-version=3.13.9`
my release app works normally, 
but when I release a new patch by command
`shorebird patch aar --release-version=1.0.0+1`
My app can not update that patch
Someone can help me please!

here is my logcat error
![Screenshot 2024-04-25 at 5 39 47 PM](https://github.com/shorebirdtech/samples/assets/18256686/1f2f9671-c2d3-4b53-b8ca-5c6d690a26f4)

here is my flutter doctor
![Screenshot 2024-04-25 at 5 42 37 PM](https://github.com/shorebirdtech/samples/assets/18256686/e7d57a2c-2445-45b4-93da-574ad93d7fc5)

**Comment by eseidel** [comment]
The updater is saying that the binary produced by `shorebird release` is not the same binary as you are running to receive the patch.

Are you using `shorebird preview` or are you running the app in some other way?

**Comment by LammPhan** [comment]
> The updater is saying that the binary produced by `shorebird release` is not the same binary as you are running to receive the patch.
> 
> Are you using `shorebird preview` or are you running the app in some other way?

No, I'm using app [Add to app](https://docs.flutter.dev/add-to-app) in flutter follow [document shorebird](https://docs.shorebird.dev/guides/hybrid-app/android). So I can't apply  `shorebird preview`  command

**Comment by eseidel** [comment]
Ah yes, it's definitely much easier to hit this error in the add2app flow.

**Comment by eseidel** [comment]
The solution here (which I think we have another bug on?) is to create some mechanism for us to version the contents of an aar, separately from the release version from the aab.

Shorebird depends on the stores enforcing one-version-per-aab rules, meaning that the version number is unique for a given set of aab contents.  If we move away from that we'll need our own uniqueness mechanism, or find some other one that Android has (maybe it already has some sort of aab/apk identifier that isn't the release version number?)

**Comment by eseidel** [comment]
https://github.com/shorebirdtech/shorebird/issues/793 has more discussion of a similar issue.

**Comment by bryanoltman** [comment]
I believe this has been fixed with https://github.com/shorebirdtech/docs/pull/291
